name: Build and Generate Provenance

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Archive web application
        run: |
          mkdir -p dist
          cp -r src requirements.txt dist/
          [ -f Procfile ] && cp Procfile dist/
          [ -f runtime.txt ] && cp runtime.txt dist/
          cd dist && zip -r python_web_app.zip . && cd ..

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-web-app
          path: dist/python_web_app.zip

  provenance:
    needs: build
    permissions:
      id-token: write
      contents: write
      actions: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.10.0
    with:
      base64-subjects: false
      upload-assets: true
      artifact-path: dist/python_web_app.zip
      output-path: dist/python_web_app.intoto.jsonl    

  verify:
    needs: provenance
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-web-app
          path: dist

      - name: Download provenance
        uses: actions/download-artifact@v4
        with:
          name: provenance
          path: dist

      - name: Verify provenance
        run: |
          curl -LO https://github.com/slsa-framework/slsa-verifier/releases/latest/download/slsa-verifier-linux-amd64
          chmod +x slsa-verifier-linux-amd64
          ./slsa-verifier-linux-amd64 verify-artifact \
            dist/python_web_app.zip \
            --provenance dist/provenance.intoto.jsonl \
            --source github.com/visgwu/python_web_app
