name: CI

on:
  push:    
    tags:
      - 'v*.*.*'   # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Archive web application
      run: |
        mkdir -p artifact
        cp -r src requirements.txt artifact/
        if [ -f Procfile ]; then cp Procfile artifact/; fi
        if [ -f runtime.txt ]; then cp runtime.txt artifact/; fi
        cd artifact
        zip -r ../python-web-app.zip .
        cd ..

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./python-web-app.zip
        asset_name: python-web-app.zip
        asset_content_type: application/zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Step
        run: echo "Deployment complete. Visit your release at https://github.com/${{ github.repository }}/releases/latest"