name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Archive web application
      run: |
        mkdir -p artifact
        cp -r src requirements.txt artifact/
        if [ -f Procfile ]; then cp Procfile artifact/; fi
        if [ -f runtime.txt ]; then cp runtime.txt artifact/; fi

    - name: Upload web application artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-web-app
        path: artifact/