name: Build and Generate Provenance

on:
  push:    
    tags:
      - 'v*.*.*'   # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Archive web application
      run: |
        mkdir -p dist
        cp -r src requirements.txt dist/
        if [ -f Procfile ]; then cp Procfile dist/; fi
        if [ -f runtime.txt ]; then cp runtime.txt dist/; fi
        cd dist
        zip -r python_web_app.zip .
        cd ..

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/python_web_app.zip
        asset_name: python_web_app.zip
        asset_content_type: application/zip

  provenance:
    needs: build
    permissions:
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.8.0
    with:
      base64-subjects: false
      upload-assets: true
      artifact-path: dist/python_web_app.zip
      output-path: dist/python_web_app.intoto.jsonl

  verify:
      needs: provenance
      runs-on: ubuntu-latest
      steps:
        - name: Download build artifact
          uses: actions/download-artifact@v4
          with:
            name: python_web_app.zip
            path: dist

        - name: Download provenance artifact
          uses: actions/download-artifact@v4
          with:
            name: provenance
            path: dist

        - name: Download SLSA Verifier
          run: |
            curl -LO https://github.com/slsa-framework/slsa-verifier/releases/latest/download/slsa-verifier-linux-amd64
            chmod +x slsa-verifier-linux-amd64

        - name: Verify SLSA Provenance
          run: |
            ./slsa-verifier-linux-amd64 verify-artifact \
              dist/python_web_app.zip \
              --provenance dist/python_web_app.intoto.jsonl \
              --source github.com/visgwu/python_web_app